is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - headers.contentTypeJson
  - errors.formatNino
  - errors.formatBusinessId
  - errors.formatFromDate
  - errors.formatToDate
  - errors.formatValue
  - errors.incorrectOrEmptyBody
  - errors.ruleBothExpensesSupplied
  - errors.ruleToDateBeforeFromDate
  - errors.ruleOverlappingPeriod
  - errors.ruleMisalignedPeriod
  - errors.ruleNotContiguousPeriod
  - errors.ruleNotAllowedConsolidatedExpenses
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Create a Self-Employment Periodic Update [test only]
description: This endpoint allows a developer to create a self-employment periodic update for submission of periodic data, for example,  incomes and expenses. Submissions which do not include any incomes or expenses are invalid. You should submit zero values if you do not have incomes or expenses. The payload must contain either expenses or consolidatedExpenses elements.
(annotations.sandboxData): !include ../scenarios/create_periodic_update_period_scenarios.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include ../schemas/create_periodic_update_period_request.json
    examples:
     example-1:
      description: Create Periodic Update Period Consolidated Request
      value: !include ../examples/create_periodic_update_period_consolidated_request.json
     example-2:
      description: Create Periodic Update Period Non-Consolidated Request
      value: !include ../examples/create_periodic_update_period_non_consolidated_request.json
responses:
  200:
    body:
      application/json:
        type: !include ../schemas/create_periodic_update_period_response.json
        examples:
          example:
            description: Example Response
            value: !include ../examples/create_periodic_update_period_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
