is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - headers.contentTypeJson
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.formatValueSE
  - errors.formatBusinessId
  - errors.ruleBildingNameNumber
  - errors.formatString
  - errors.ruleBothAllowancesSupplied
  - errors.ruleAllowanceNotSupported
  - errors.incorrectOrEmptyBody
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
  - errors.formatDate
  - errors.formatClass4Exemption
displayName: Create and Amend Self-Employment Annual Submission [test only]
description: This end point allows a developer to create or amend a self-employment annual summary for a tax year. A National Insurance number, Business ID and tax year must be provided.
(annotations.sandboxData): !include ../scenarios/create_and_amend_annual_submission_scenarios.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include ../schemas/create_and_amend_annual_submission_request.json
    examples:
      example-1:
        description: Response With Trading Income Allowance Request
        value: !include ../examples/create_and_amend_with_trading_income_allowance.json
      example-2:
        description: Response Without Trading Income Allowance Request
        value: !include ../examples/create_and_amend_without_trading_income_allowance.json
responses:
  200:
    body:
      application/json:
        type: !include ../schemas/create_and_amend_annual_submission_response.json
        examples:
          example:
            description: Example Response
            value: !include ../examples/create_and_amend_annual_submission_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
