is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatBusinessId
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: List all self-employment update periods [test only]
description: This endpoint allows a developer to retrieve a list of all self-employment update periods. A National Insurance number and Business ID must be provided.
(annotations.sandboxData): !include ../scenarios/retrieve_list_periodic_update_period_scenarios.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include ../schemas/retrieve_list_periodic_update_period_response.json
        examples:
          example-1:
            description: Example Response
            value: !include ../examples/retrieve_list_periodic_update_period_response.json
          example-2:
            description: Response with Multiple Periods
            value: !include ../examples/retrieve_list_periodic_update_period_multiple_periods_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
